#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


class PredicateEntry
  include ::Thrift::Struct, ::Thrift::Struct_Union
  DEFINITION_ID = 1
  ENTITY_ID = 2

  FIELDS = {
    DEFINITION_ID => {:type => ::Thrift::Types::I32, :name => 'definition_id'},
    ENTITY_ID => {:type => ::Thrift::Types::I32, :name => 'entity_id'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class AssociationEntry
  include ::Thrift::Struct, ::Thrift::Struct_Union
  DEFINITION_ID = 1
  ENTITY_ID = 2
  ASSOCIATED_ENTITY_ID = 3

  FIELDS = {
    DEFINITION_ID => {:type => ::Thrift::Types::I32, :name => 'definition_id'},
    ENTITY_ID => {:type => ::Thrift::Types::I32, :name => 'entity_id'},
    ASSOCIATED_ENTITY_ID => {:type => ::Thrift::Types::I32, :name => 'associated_entity_id'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Suggestions
  include ::Thrift::Struct, ::Thrift::Struct_Union
  ENTITIES_IDS = 1
  MATCHES_COUNT = 2

  FIELDS = {
    ENTITIES_IDS => {:type => ::Thrift::Types::LIST, :name => 'entities_ids', :element => {:type => ::Thrift::Types::I32}},
    MATCHES_COUNT => {:type => ::Thrift::Types::I32, :name => 'matches_count'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

