#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None



class Predicate:
  """
  Attributes:
   - definition_id
   - entity_id
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'definition_id', None, None, ), # 1
    (2, TType.I32, 'entity_id', None, None, ), # 2
  )

  def __init__(self, definition_id=None, entity_id=None,):
    self.definition_id = definition_id
    self.entity_id = entity_id

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.definition_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.entity_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Predicate')
    if self.definition_id is not None:
      oprot.writeFieldBegin('definition_id', TType.I32, 1)
      oprot.writeI32(self.definition_id)
      oprot.writeFieldEnd()
    if self.entity_id is not None:
      oprot.writeFieldBegin('entity_id', TType.I32, 2)
      oprot.writeI32(self.entity_id)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class Association:
  """
  Attributes:
   - definition_id
   - entity_id
   - associated_entity_id
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'definition_id', None, None, ), # 1
    (2, TType.I32, 'entity_id', None, None, ), # 2
    (3, TType.I32, 'associated_entity_id', None, None, ), # 3
  )

  def __init__(self, definition_id=None, entity_id=None, associated_entity_id=None,):
    self.definition_id = definition_id
    self.entity_id = entity_id
    self.associated_entity_id = associated_entity_id

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.definition_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.entity_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.associated_entity_id = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Association')
    if self.definition_id is not None:
      oprot.writeFieldBegin('definition_id', TType.I32, 1)
      oprot.writeI32(self.definition_id)
      oprot.writeFieldEnd()
    if self.entity_id is not None:
      oprot.writeFieldBegin('entity_id', TType.I32, 2)
      oprot.writeI32(self.entity_id)
      oprot.writeFieldEnd()
    if self.associated_entity_id is not None:
      oprot.writeFieldBegin('associated_entity_id', TType.I32, 3)
      oprot.writeI32(self.associated_entity_id)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
